global using System.ComponentModel.DataAnnotations;
global using System.Net.Http.Json;
global using Fakrny.Blazor.Components;
global using Fakrny.Blazor.Models;
global using Fakrny.Blazor.Models.Dtos;
global using Fakrny.Blazor.Services;
global using Microsoft.AspNetCore.Components;
global using Microsoft.AspNetCore.Components.Forms;
global using MudBlazor;
